# YOLOv5 ğŸš€ by YOLOAir, GPL-3.0 license
# parameters
nc: 2  # number of classes
depth_multiple: 1.0  # model depth multiple
width_multiple: 1.0  # layer channel multiple

# anchors
anchors:
  - [12,16, 19,36, 40,28]  # P3/8
  - [36,75, 76,55, 72,146]  # P4/16
  - [142,110, 192,243, 459,401]  # P5/32

# yolov7 backbone
backbone:
  # [from, number, module, args]
  [[-1, 1, Conv, [32, 3, 1]],  # 0
   [-1, 1, Conv, [64, 3, 2]],  # 1-P1/2     320*320*64
   [-1, 1, Conv, [64, 3, 1]],
   [-1, 1, Conv, [128, 3, 2]],  # 3-P2/4    160*160*128

   [-1, 1, Conv, [64, 1, 1]],
   [-2, 1, Conv, [64, 1, 1]],
   [-1, 1, Conv, [64, 3, 1]],
   [-1, 1, Conv, [64, 3, 1]],
   [-1, 1, Conv, [64, 3, 1]],
   [-1, 1, Conv, [64, 3, 1]],
   [[-1, -3, -5, -6], 1, Concat, [1]],
   [-1, 1, Conv, [256, 1, 1]],  # 11        Elanç»“æ„ï¼Œé€šé“æ•°ä¹˜2ï¼Œ160*160*256     Elanç»“æ„å°±æ˜¯é€šé“æ•°ä¹˜4

   [-1, 1, MP, []],                          #Maxpooling
   [-1, 1, Conv, [128, 1, 1]],
   [-3, 1, Conv, [128, 1, 1]],
   [-1, 1, Conv, [128, 3, 2]],
   [[-1, -3], 1, Concat, [1]],  # 16-P3/8    MP1ä¸‹é‡‡æ ·ï¼Œå°ºå¯¸å˜ä¸º80*80*256        é€šé“æ•°ä¹˜2ï¼Œä¸‹é‡‡æ ·å°ºåº¦å˜ä¸º0.5

   [-1, 1, Conv, [128, 1, 1]],
   [-2, 1, Conv, [128, 1, 1]],
   [-1, 1, Conv, [128, 3, 1]],
   [-1, 1, Conv, [128, 3, 1]],
   [-1, 1, Conv, [128, 3, 1]],
   [-1, 1, Conv, [128, 3, 1]],
   [[-1, -3, -5, -6], 1, Concat, [1]],
   [-1, 1, Conv, [512, 1, 1]],  # 24       Elanç»“æ„ï¼Œé€šé“æ•°ä¹˜2ï¼Œ80*80*512
         
   [-1, 1, MP, []],
   [-1, 1, Conv, [256, 1, 1]],
   [-3, 1, Conv, [256, 1, 1]],
   [-1, 1, Conv, [256, 3, 2]],
   [[-1, -3], 1, Concat, [1]],  # 29-P4/16    MP1ä¸‹é‡‡æ ·ï¼Œå°ºå¯¸å˜ä¸º40*40*512

   [-1, 1, Conv, [256, 1, 1]],
   [-2, 1, Conv, [256, 1, 1]],
   [-1, 1, Conv, [256, 3, 1]],
   [-1, 1, Conv, [256, 3, 1]],
   [-1, 1, Conv, [256, 3, 1]],
   [-1, 1, Conv, [256, 3, 1]],
   [[-1, -3, -5, -6], 1, Concat, [1]],
   [-1, 1, Conv, [1024, 1, 1]],  # 37         Elanç»“æ„ï¼Œé€šé“æ•°ä¹˜2ï¼Œ40*40*1024
         
   [-1, 1, MP, []],
   [-1, 1, Conv, [512, 1, 1]],
   [-3, 1, Conv, [512, 1, 1]],
   [-1, 1, Conv, [512, 3, 2]],
   [[-1, -3], 1, Concat, [1]],  # 42-P5/32    MP1ä¸‹é‡‡æ ·ï¼Œå°ºå¯¸å˜ä¸º20*20*1024

   [-1, 1, Conv, [256, 1, 1]],
   [-2, 1, Conv, [256, 1, 1]],
   [-1, 1, Conv, [256, 3, 1]],
   [-1, 1, Conv, [256, 3, 1]],
   [-1, 1, Conv, [256, 3, 1]],
   [-1, 1, Conv, [256, 3, 1]],
   [[-1, -3, -5, -6], 1, Concat, [1]],        #Elanç»“æ„ï¼Œç›¸åŠ è¾“å‡ºä¸ºè¾“å…¥çš„ä¸¤å€
   [-1, 1, Conv, [1024, 1, 1]],  # 50        Elanç»“æ„ï¼Œ256ä¹˜4ï¼Œ20*20*1024
   [-1,1,CA,[1024]]                #åŠ å…¥CAæ³¨æ„åŠ›æœºåˆ¶
  ]

# yolov7 head
head:
  [[-1, 1, SPPCSPC, [512]], # 51         SPPCSPCç»“æ„ï¼Œé€šé“æ•°å˜ä¸º512ï¼Œ20*20*512
  
   [-1, 1, Conv, [256, 1, 1]],                              #20*20*256
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],              #ä¸Šé‡‡æ ·40*40*256
   [37, 1, Conv, [256, 1, 1]], # route backbone P4          #å°†37å±‚çš„ç‰¹å¾å›¾ï¼Œç»è¿‡CBSï¼Œå˜ä¸º40*40*256
   [[-1, -2], 1, BiFPN_Add2, [256,256]],                    #ç›¸åŠ ï¼Œå˜ä¸º40*40*512                                   cat
   
   [-1, 1, Conv, [256, 1, 1]],
   [-2, 1, Conv, [256, 1, 1]],
   [-1, 1, Conv, [128, 3, 1]],
   [-1, 1, Conv, [128, 3, 1]],
   [-1, 1, Conv, [128, 3, 1]],
   [-1, 1, Conv, [128, 3, 1]],
   [[-1, -2, -3, -4, -5, -6], 1, Concat, [1]],              #Elan-Hæ¨¡å—ï¼Œå˜ä¸ºäº†40*40*1024
   [-1, 1, Conv, [256, 1, 1]], # 63                         40*40*256
   
   [-1, 1, Conv, [128, 1, 1]],                              #40*40*128
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],              #80*80*128
   [24, 1, Conv, [128, 1, 1]], # route backbone P3          #å°†24å±‚çš„ç‰¹å¾å›¾80*80*512ï¼Œå˜ä¸º80*80*128
   [[-1, -2], 1, BiFPN_Add2, [128,128]],                    #ç›¸åŠ ï¼Œå˜ä¸º80*80*256                                 cat
   
   [-1, 1, Conv, [128, 1, 1]],
   [-2, 1, Conv, [128, 1, 1]],
   [-1, 1, Conv, [64, 3, 1]],
   [-1, 1, Conv, [64, 3, 1]],
   [-1, 1, Conv, [64, 3, 1]],
   [-1, 1, Conv, [64, 3, 1]],
   [[-1, -2, -3, -4, -5, -6], 1, Concat, [1]],              # Elanç»“æ„ï¼Œ80*80*512
   [-1, 1, Conv, [128, 1, 1]], # 76                           80*80*128
      
   [-1, 1, MP, []],
   [-1, 1, Conv, [128, 1, 1]],                              #40*40*128
   [-3, 1, Conv, [128, 1, 1]],
   [-1, 1, Conv, [128, 3, 2]],                              #40*40*128
   #[[-1, -3, 64], 1, Concat, [1]],                          #MP2ä¸‹é‡‡æ ·ï¼Œ-1å±‚å’Œ-3å±‚è¾“å…¥ç›¸åŠ ä¸º40*40*256ï¼Œå’Œ64å±‚40*40*256ç›¸åŠ å¾—40*40*512    cat
   [[-1, -3], 1, Concat, [1]],
   [[-1, 64], 1, BiFPN_Add2, [256,256]],

   [-1, 1, Conv, [256, 1, 1]],
   [-2, 1, Conv, [256, 1, 1]],
   [-1, 1, Conv, [128, 3, 1]],
   [-1, 1, Conv, [128, 3, 1]],
   [-1, 1, Conv, [128, 3, 1]],
   [-1, 1, Conv, [128, 3, 1]],
   [[-1, -2, -3, -4, -5, -6], 1, Concat, [1]],              #40*40*1024
   [-1, 1, Conv, [256, 1, 1]], # 89                         40*40*256
      
   [-1, 1, MP, []],                                        #20*20*256
   [-1, 1, Conv, [256, 1, 1]],                             #20*20*256
   [-3, 1, Conv, [256, 1, 1]],                             #40*40*256
   [-1, 1, Conv, [256, 3, 2]],                             #20*20*256
   #[[-1, -3, 52], 1, Concat, [1]],                         #MP2ä¸‹é‡‡æ ·ï¼Œ-1å±‚å’Œ-3å±‚è¾“å…¥ç›¸åŠ ä¸º20*20*512ï¼Œå’Œ52å±‚20*20*512ç›¸åŠ å¾—20*20*1024     cat
   [[-1, -3], 1, Concat, [1]],
   [[-1, 52], 1, BiFPN_Add2, [512,512]],

   [-1, 1, Conv, [512, 1, 1]],
   [-2, 1, Conv, [512, 1, 1]],
   [-1, 1, Conv, [256, 3, 1]],
   [-1, 1, Conv, [256, 3, 1]],
   [-1, 1, Conv, [256, 3, 1]],
   [-1, 1, Conv, [256, 3, 1]],
   [[-1, -2, -3, -4, -5, -6], 1, Concat, [1]],            #ELan-H,20*20*2048
   [-1, 1, Conv, [512, 1, 1]], # 102                      20*20*512
   
   [76, 1, RepConv, [256, 3, 1]],                       #REPVGG+CONV 80*80*256
   [90, 1, RepConv, [512, 3, 1]],                       #40*40*512
   [103, 1, RepConv, [1024, 3, 1]],                     #20*20*1024

   [[104,105,106], 1, IAuxDetect, [nc, anchors]],   # Detect(P3, P4, P5)
  ]
